name: Release

# Controls when the workflow will run
on:
  # on release published
  release:
    types: [published]

#   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # bump the version found in RemCordPlugin/public/manifest.json to the version of the release
      - name: bump version
        run: |
          # get the version of the release
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/v//')
          # get the major, minor, and patch version
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          # replace the version in the manifest.json
          sed -i "s/\"major\": [0-9]*/\"major\": $MAJOR/" RemCordPlugin/public/manifest.json
          sed -i "s/\"minor\": [0-9]*/\"minor\": $MINOR/" RemCordPlugin/public/manifest.json
          sed -i "s/\"patch\": [0-9]*/\"patch\": $PATCH/" RemCordPlugin/public/manifest.json

      # Runs a single command using the runners shell
      - name: install zip
        run: sudo apt-get install zip

      # delete dist folder
      - name: delete dist folder
        run: rm -rf dist

      # Runs a set of commands using the runners shell
      - name: zip the folder RemCordPlugin into a zip file and make it in dist folder
        run: |
          mkdir dist
          zip -r -j ../dist/RemCordPlugin.zip RemCordPlugin
          cd ..

      - name: upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: dist
